name: copies
on:
  push:
    branches:
      - '**'
jobs:
  sass:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: cp TangerineUI.css mastodon/app/javascript/styles/tangerineui/layout-single-column.scss
      - run: cp TangerineUI-purple.css mastodon/app/javascript/styles/tangerineui-purple/layout-single-column.scss
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Copy CSS files to installation folder
          file_pattern: 'mastodon/'
